CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    name TEXT NOT NULL
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE notes (
    id uuid DEFAULT uuid_generate_v4 (), 
    name TEXT NOT NULL,
    modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    folderId INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    content TEXT DEFAULT '' 
);

