CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE noteful_notes (
    id uuid DEFAULT uuid_generate_v4 (), 
    name TEXT NOT NULL,
    folderId INTEGER NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    name TEXT NOT NULL
);

INSERT INTO noteful_notes (
    name,
    folderId,
    content
)

VALUES (
    'New Note', 1, 'This is just a test'
)